name: Actions CI - Next.js Build & Deploy

on:
  push:
    branches: [ main ]

# 设置权限
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 获取源码  
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 避免认证问题

    - name: 设置 Node.js 环境  
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 安装 pnpm  
      run: |
        npm install -g pnpm
        pnpm --version  # 确保安装成功

    - name: 安装依赖  
      run: pnpm install

    - name: 构建 Next.js 15  
      run: |
        pnpm run build
        # 确保关键文件存在
        mkdir -p out 
        touch out/.nojekyll
        # 复制静态404页面到out目录根目录
        cp public/404.html out/404.html || echo "No 404.html file to copy"
        # 创建index.html，如果不存在
        [ -f out/index.html ] || echo '<meta http-equiv="refresh" content="0;url=/private_house/" />' > out/index.html
        # 输出构建结果的文件列表，便于排查
        ls -la out/

    - name: 部署到 GitHub Pages  
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: out
        clean: true
        commit-message: "部署更新: ${{ github.event.head_commit.message }}"
